apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-management-api
spec:
  rules:
    - host: api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-management-api
                port:
                  number: 80
